version: '3.8'

services:
  database:
    image: postgres:alpine
    restart : always
    expose:
    - "4365"
    ports:
    - "4365:4365"
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
    command: -p 4365